### ISSUE TITLE
User got deleted/removed from localstorage whenever I do a refresh

### ISSUE THREAD

**Issue by trishitchar** [trishitchar/AI-flix#1] opened 2024-09-11 21:25 UTC
I already tried several methods like changing `http option`, `same site`, and others too

you can  find the code for cookie setting in 
frontend : components-> login.jsx, hooks-> useAuthMiddleware.js
server : controllers -> userController.js

**Comment by trishitchar** [comment] 2024-09-14 00:10
the token is there already, but sometimes got vanished while refreshing
but things working fine 
and also if i perform some action then it come again

**Comment by Jai-Marothiya** [comment] 2024-10-03 04:49
Hello @trishitchar - I believe, I can fix this issue. Please assign it to me.

**Comment by trishitchar** [comment] 2024-10-10 20:52
Sorry for the late reply 
I was busy in another project 
Please do proceed with your logic

**Comment by Jai-Marothiya** [comment] 2024-10-17 03:27
Hi @trishitchar - I'm not able to reproduce this issue locally. Can you tell me the steps?

**Comment by trishitchar** [comment] 2024-10-17 10:06
I know that's why I was also frustrated..
locally everything is working fine,
but sometimes in production it's not working
you can check the ```cookie storing methods```
the issue will not hampering any workflow
otherwise leave it someday I'll fix it

**Closed as completed** 2024-10-18 13:47 UTC
Labels: bug, enhancement
